# Site settings
# Enter your own credentials here
title: "Processing-Structure Linkages"
email: dpatel73@gatech.edu
description: >
  Tell us about your site
baseurl: "/MIC-Mg-PSLinkages" # replace ``/research-pages`` with the name of the parents repository
url: "Materials-Informatics-Class-Fall2014.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: PenPatel
  repo: MIC-Mg-PSLinkages
  # Branch hosting Github pages
  branch: gh-pages
